//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSM.DAL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceResponse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceResponse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSM.DAL.Resource.ResourceResponse", typeof(ResourceResponse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Sucessfully Added.
        /// </summary>
        public static string AddedSucessfully {
            get {
                return ResourceManager.GetString("AddedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Sucessfully.
        /// </summary>
        public static string ApprovedSucessfully {
            get {
                return ResourceManager.GetString("ApprovedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Bar Code Already Exists In Asset Master.
        /// </summary>
        public static string BarCodeAlreadyExists {
            get {
                return ResourceManager.GetString("BarCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Not Assigned For This Activity.
        /// </summary>
        public static string BarcodeNotAssignedForThisActivity {
            get {
                return ResourceManager.GetString("BarcodeNotAssignedForThisActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Not Found In Asset Libray.
        /// </summary>
        public static string BarcodeNotFoundInAssetLibray {
            get {
                return ResourceManager.GetString("BarcodeNotFoundInAssetLibray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckList Created Successfully.
        /// </summary>
        public static string CheckListCreatedSuccessfully {
            get {
                return ResourceManager.GetString("CheckListCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Deleted Sucessfully.
        /// </summary>
        public static string DeletedSucessfully {
            get {
                return ResourceManager.GetString("DeletedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.Please Contact System Admin.
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Error Has Occurred.
        /// </summary>
        public static string FailureMessage {
            get {
                return ResourceManager.GetString("FailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem in uploading file please try again later.
        /// </summary>
        public static string FileUploaderFailure {
            get {
                return ResourceManager.GetString("FileUploaderFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded Successfully.
        /// </summary>
        public static string FileUploaderSuccess {
            get {
                return ResourceManager.GetString("FileUploaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Closed Successfully.
        /// </summary>
        public static string JobClosedSuccessfully {
            get {
                return ResourceManager.GetString("JobClosedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Job Is Not Completely Created Please Check.
        /// </summary>
        public static string JobNotCompletelyCreated {
            get {
                return ResourceManager.GetString("JobNotCompletelyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Job Not Yet Completed.
        /// </summary>
        public static string JobNotYetCompleted {
            get {
                return ResourceManager.GetString("JobNotYetCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Login Please Try Again Later.
        /// </summary>
        public static string LoginUnSuccessful {
            get {
                return ResourceManager.GetString("LoginUnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved Successfully.
        /// </summary>
        public static string MovedSuccessfully {
            get {
                return ResourceManager.GetString("MovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found.
        /// </summary>
        public static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Jobs Assigned For Admin.
        /// </summary>
        public static string NoJobsAssignedAdmin {
            get {
                return ResourceManager.GetString("NoJobsAssignedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Jobs Assigned For Super Admin.
        /// </summary>
        public static string NoJobsAssignedSuperAdmin {
            get {
                return ResourceManager.GetString("NoJobsAssignedSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Suggestions Found.
        /// </summary>
        public static string NoSuggestionsFound {
            get {
                return ResourceManager.GetString("NoSuggestionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Sucessfully.
        /// </summary>
        public static string RejectedSucessfully {
            get {
                return ResourceManager.GetString("RejectedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Updated Sucessfully.
        /// </summary>
        public static string UpdatedSucessfully {
            get {
                return ResourceManager.GetString("UpdatedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This UserName Is Already Taken.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does Not Exists.
        /// </summary>
        public static string UserDoesNotExists {
            get {
                return ResourceManager.GetString("UserDoesNotExists", resourceCulture);
            }
        }
    }
}
